package vn.edu.hust.student.dynamicpool.events;

public enum EventType {
	COLISSION, 
	BLL_JOIN_HOST_WHITH_A_KEY, 
	BLL_CREATE_HOST, 
	BLL_ADD_DEVICE, 
	DAL_JOIN_HOST, 
	DAL_ADD_DEVICE_RESPOND, 
	DAL_CREATE_HOST, 
	DAL_CREATE_FISH_RESPOND, 
	DAL_REMOVE_FISH, 
	PRS_ENTER_SCREEN_SIZE, 
	PRS_ENTER_KEY, 
	BLL_CREATE_FISH, 
	DAL_ADD_FISH_REQUEST, 
	DAL_ADD_DEVICE_REQUEST,
	DAL_UDPATE_SETTINGS_RESPONSE
}
