package vn.edu.hust.student.dynamicpool.events;

public enum EventType {
	PRS_ENTER_KEY, 
	PRS_ENTER_SCREEN_SIZE, 
	BLL_CREATE_HOST, 
	BLL_JOIN_HOST_WHITH_A_KEY, 
	BLL_ADD_DEVICE, 
	BLL_CREATE_FISH, 
	DAL_CREATE_HOST, 
	DAL_JOIN_HOST, 
	DAL_ADD_DEVICE_REQUEST,
	DAL_UPDATE_SETTINGS_RESPONSE,
	DAL_CREATE_FISH_REQUEST, 
	DAL_CREATE_FISH_RESPOND, 
	DAL_SEND_FISH_RESPONSE,
	DAL_REMOVE_FISH
}
